# numpy 


### List :
   * List store data in a non contiguous memory allocation
   * Non-contigugous memory allocaton program is divided into severel parts placed in a diffrernet paert of the
     main memory.
   * very slow for mathematicaloperation

### Array:
   * Array stores data in acontiguous memory allocation.
   * It is very fast for mathematical operation.
   * very fast becasue parcially code was writtern in c and c++.

## What is NumPy?
  * NumPy is a Python library used for working with arrays.

  * It also has functions for working in domain of linear algebra, fourier transform, and matrices.

  * NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

  * NumPy stands for Numerical Python.

## Why Use NumPy?
  * In Python we have lists that serve the purpose of arrays, but they are slow to process.

  * NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

  * The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with     ndarray very easy.

  * Arrays are very frequently used in data science, where speed and resources are very important.
  
  
## Why is NumPy Faster Than Lists?
   * NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and                manipulate them very efficiently.

   * This behavior is called locality of reference in computer science.

   * This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU              architectures.

## Which Language is NumPy written in?
   * NumPy is a Python library and is written partially in Python, but most of the parts that require fast              computation are written in C or C++.

## Where is the NumPy Codebase?
   * The source code for NumPy is located at this github repository https://github.com/numpy/numpy



In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [2]:
np.__version__

'1.19.5'

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


## 0-D Arrays
   * 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [4]:
import numpy as np

arr = np.array(42)

print(arr)

42


## 1-D Arrays
  * An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

  * These are the most common and basic arrays.

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## 2-D Arrays
  * An array that has 1-D arrays as its elements is called a 2-D array.

  * These are often used to represent matrix or 2nd order tensors.

In [7]:
arr=np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(arr)

[[1 2 3 4 5]
 [5 4 3 2 1]]


## 3-D arrays
  * An array that has 2-D arrays (matrices) as its elements is called 3-D array.

  * These are often used to represent a 3rd order tensor.

In [9]:
arr=np.array([[[1,2,3,4,5],[5,4,3,2,1]],[[6,7,8,9,0],[0,9,8,7,6]]])
print(arr)

[[[1 2 3 4 5]
  [5 4 3 2 1]]

 [[6 7 8 9 0]
  [0 9 8 7 6]]]


In [10]:
arr.ndim # return the dimension of the array

3

## accessing array element 

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [14]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[1][1])

7


In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0][1][2])

6


## Slicing array

In [16]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


## Numpy data types

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

In [18]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [19]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


## changing data type
 * The best way to change the data type of an existing array, is to make a copy of the array with the astype()        method.

 * The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.



In [20]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


## shape of the array

In [23]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


## reshape array

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## Flattening Array

In [29]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


## Array iteration

In [30]:

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [31]:
arr = np.array([[1, 2, 3],[6,7,8]])

for x in arr:
  print(x)

[1 2 3]
[6 7 8]


## enumerate iteration


In [34]:
arr = np.array([3, 5, 8])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 3
(1,) 5
(2,) 8


## joining arrays

In [35]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## splitting array

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


## search array and search sorted
* There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [38]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


## sorting Array

In [39]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


## Array Filter


In [40]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


## What is a Random Number?
* Random number does NOT mean a different number every time. Random means something that can not be predicted logically

In [45]:
x = np.random.randint(100) #every time run  generate random numbers

print(x)


37


In [48]:
# Generating random float between 0 tp 1
x = np.random.rand()

print(x)

0.3776281114904525


In [50]:
x=np.random.randint(100, size=(5)) # range of random numbers

print(x)

[99 26 52 79 61]


In [51]:
x=np.random.randint(100, size=(5,5)) # range of random numbers

print(x)

[[95 65 32 44 11]
 [14  4 77 24 68]
 [89 71 53 31 47]
 [96  4 70 16 36]
 [ 8 82 78 11 89]]


In [58]:
# based on the choice return value
x = np.random.choice([3, 5, 7, 9])

print(x)

5


In [59]:
x = np.random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 5 5 3 5]
 [7 7 3 7 3]
 [9 9 3 5 9]]


## What is Data Distribution?
* Data Distribution is a list of all possible values, and how often each value occurs.

* Such lists are important when working with statistics and data science.

* The random module offer methods that returns randomly generated data distributions.

## Random Distribution
A random distribution is a set of random numbers that follow a certain probability density function.

In [60]:
x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(50))

print(x)

[7 7 7 5 7 7 7 5 5 5 7 7 7 5 7 5 7 7 7 5 7 5 7 7 7 7 7 5 3 7 3 5 7 5 7 7 5
 7 7 5 7 7 7 3 5 7 7 7 7 5]


## Normal distribution

In [63]:
x = np.random.normal(size=(2, 3))

print(x)

[[ 0.18985705 -1.86172712  0.40743776]
 [-0.2057588  -0.42418021  0.88408413]]


## np arange

In [64]:
import numpy as np
x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [66]:
x=np.arange(1,20,step=2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


## Numpy Linspace

In [67]:
x=np.linspace(1,10,50)
print(x)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [71]:
x=np.ones((2,4),dtype=int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [72]:
x=np.zeros((2,4),dtype=int)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])